-- PostgreSQL Schema for MY_ADG_DEV

CREATE TABLE IF NOT EXISTS T_DeXuat(
	ID SERIAL NOT NULL,
	TenDeXuat VARCHAR(200) NULL,
	LoaiDeXuat INT NULL,
	Status INT NULL,
	GhiChu VARCHAR(500) NULL,
	CreatedDate TIMESTAMP NULL,
	CreateBy INT NULL,
	ModifyDate TIMESTAMP NULL,
	ModifyBy INT NULL
);

CREATE TABLE IF NOT EXISTS T_FILE(
	FILE_ID SERIAL NOT NULL,
	SERVICE VARCHAR(350) NULL,
	NAME VARCHAR(350) NULL,
	LINK VARCHAR(350) NULL,
	CONSTRAINT PK_T_FILE PRIMARY KEY (FILE_ID)
);

CREATE TABLE IF NOT EXISTS T_FUNCTION(
	FUNCTION_ID SERIAL NOT NULL,
	FUNCTION_NAME VARCHAR(100) NULL,
	DISPLAY_NAME VARCHAR(150) NULL,
	PARENT_ID INT NULL,
	PAGE_URL VARCHAR(500) NULL,
	MENU_ID INT NULL,
	TYPE VARCHAR(10) NULL,
	STATUS INT NULL,
	CREATED_DATE TIMESTAMP NULL,
	SORT_ORDER INT NULL,
	ICON VARCHAR(100) NULL,
	CONSTRAINT PK_T_FUNCTION PRIMARY KEY (FUNCTION_ID)
);

CREATE TABLE IF NOT EXISTS T_Menu(
	Id SERIAL NOT NULL,
	classIcon VARCHAR(100) NULL,
	classMenu VARCHAR(100) NULL,
	IdParent INT NULL,
	isToogle BOOLEAN NULL DEFAULT FALSE,
	ignoreCheck BOOLEAN NULL DEFAULT FALSE,
	isSelected BOOLEAN NULL DEFAULT FALSE,
	routerLink VARCHAR(200) NULL,
	menuName VARCHAR(100) NULL,
	menuPath VARCHAR(200) NULL,
	idx INT NULL,
	status BOOLEAN NULL,
	CONSTRAINT PK_T_Menu PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS T_PO_DATA(
	PO_DATA_ID SERIAL NOT NULL,
	DocType VARCHAR(50) NULL,
	Number VARCHAR(100) NULL,
	Date TIMESTAMP NULL,
	Status VARCHAR(50) NULL,
	AuthorId INT NULL,
	Author VARCHAR(100) NULL,
	ResponsibilityId INT NULL,
	Responsibility VARCHAR(100) NULL,
	Company VARCHAR(100) NULL,
	Bu VARCHAR(100) NULL,
	Amount NUMERIC(18, 2) NULL,
	Currency VARCHAR(100) NULL,
	Description VARCHAR(350) NULL,
	Comment VARCHAR(350) NULL,
	HtmlPresentation VARCHAR(350) NULL,
	PreviousDraftID VARCHAR(350) NULL,
	PoStatus INT NULL,
	CreatedDate TIMESTAMP NULL,
	CreateBy INT NULL,
	ModifyDate TIMESTAMP NULL,
	ModifyBy INT NULL,
	CONSTRAINT PK_T_PO_DATA PRIMARY KEY (PO_DATA_ID)
);

CREATE TABLE IF NOT EXISTS T_PoFlowStage(
	PO_FlowStage_ID SERIAL NOT NULL,
	PODataId INT NULL,
	Step INT NULL,
	Performer VARCHAR(100) NULL,
	DeadlineDays INT NULL,
	Description VARCHAR(350) NULL,
	StartDate TIMESTAMP NULL,
	CompletionDate TIMESTAMP NULL,
	Result INT NULL,
	PerformComment VARCHAR(350) NULL,
	ApproveLink VARCHAR(350) NULL,
	RejectLink VARCHAR(350) NULL,
	CONSTRAINT PK_T_PoFlowStage PRIMARY KEY (PO_FlowStage_ID)
);

CREATE TABLE IF NOT EXISTS T_REF_FILE_PO(
	Id SERIAL NOT NULL,
	FileId INT NULL,
	PoDataId INT NULL,
	CONSTRAINT PK_T_REF_FILE_PO PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS T_REF_ROLE_GROUP_FUNCTION(
	ROLE_GROUP_FUNCTION_ID SERIAL NOT NULL,
	ROLE_GROUP_ID INT NULL,
	FUNCTION_ID INT NULL,
	USER_VIEW BOOLEAN NULL,
	USER_NEW BOOLEAN NULL,
	USER_EDIT BOOLEAN NULL,
	USER_DELETE BOOLEAN NULL,
	USER_APPROVE BOOLEAN NULL,
	USER_REJECT BOOLEAN NULL,
	CONSTRAINT PK_T_REF_ROLE_GROUP_FUNCTION PRIMARY KEY (ROLE_GROUP_FUNCTION_ID)
);

CREATE TABLE IF NOT EXISTS T_REF_USER_ROLE_GROUP(
	USER_ROLE_GROUP_ID SERIAL NOT NULL,
	USER_ID INT NULL,
	ROLE_GROUP_ID INT NULL,
	CONSTRAINT PK_T_REF_USER_ROLE_GROUP PRIMARY KEY (USER_ROLE_GROUP_ID)
);

CREATE TABLE IF NOT EXISTS T_ROLE_GROUP(
	ROLE_GROUP_ID SERIAL NOT NULL,
	ROLE_GROUP_NAME VARCHAR(200) NULL,
	STATUS INT NULL,
	CREATED_DATE TIMESTAMP NULL,
	CONSTRAINT PK_T_ROLE_GROUP PRIMARY KEY (ROLE_GROUP_ID)
);

CREATE TABLE IF NOT EXISTS T_USER(
	USER_ID SERIAL NOT NULL,
	USER_NAME VARCHAR(150) NULL,
	PASSWORD VARCHAR(150) NULL,
	FULL_NAME VARCHAR(150) NULL,
	STATUS INT NULL,
	EMAIL VARCHAR(150) NULL,
	MOBILE VARCHAR(150) NULL,
	USER_TYPE INT NULL,
	GENDER INT NULL,
	BIRTHDAY TIMESTAMP NULL,
	ID_OR_PASSPORT VARCHAR(30) NULL,
	ADDRESS VARCHAR(350) NULL,
	JOB_DESCRIPTION VARCHAR(350) NULL,
	IS_DELETED INT NULL,
	AVATAR VARCHAR(300) NULL
);

CREATE TABLE IF NOT EXISTS T_USER_TYPE(
	USER_TYPE_ID SERIAL NOT NULL,
	USER_TYPE_NAME VARCHAR(50) NULL,
	STATUS INT NULL,
	DESCRIPTION VARCHAR(500) NULL,
	CONSTRAINT PK_T_ROLE PRIMARY KEY (USER_TYPE_ID)
);